### ISSUE TITLE
Trust Contact Sensor (CSW_ADUROLIGHT)  state is inverted?

### ISSUE THREAD

**Issue by Kryzek** [Koenkk/zigbee-shepherd-converters#220] opened 2019-01-17 16:06 UTC
Contact ON (meaning door closed):
```
Received zigbee message of type 'statusChange' with data '{"cid":"ssIasZone","zoneStatus":32}' of device 'CSW_ADUROLIGHT' (0x00158d0001cca9aa)
MQTT publish: topic 'zigbee2mqtt/0x00158d0001cca9aa', payload '{"contact":false,"linkquality":13}'
```

Contact OFF (door open):
```
Received zigbee message of type 'statusChange' with data '{"cid":"ssIasZone","zoneStatus":33}' of device 'CSW_ADUROLIGHT' (0x00158d0001cca9aa)
MQTT publish: topic 'zigbee2mqtt/0x00158d0001cca9aa', payload '{"contact":true,"linkquality":10}'
```
So this causes Home Assistant to tell that door is closed when it's open and other way around. I'm not sure how to invert the logic here.

**Comment by Koenkk** [comment] 2019-01-17 20:11
The state is right, when the door is closed there is contact (true), when open there is not (false). It is a contact sensor, not a door sensor.

**Comment by Kryzek** [comment] 2019-01-18 05:52
This is what I expect too. But MQTT payloads do not reflect this.

I'm sorry if I did not explain myself good enough (english isn't my first language) in the first post since I didn't state clearly enough that MQTT payloads are the things that I feel to be inverted.

As you said, "when door is closed there is contact (**true**)" the MQTT payloads says **false**:
Closing the door does this:
```
Received zigbee message of type 'statusChange' with data '{"cid":"ssIasZone","zoneStatus":32}' of device 'CSW_ADUROLIGHT' (0x00158d0001cca9aa)
MQTT publish: topic 'zigbee2mqtt/0x00158d0001cca9aa', payload '{"contact":false,"linkquality":13}'
```
And to be confirm it looks like this on Home Assistant when we look at the entity when door is closed (icon shows as an open door):
![door_closed](https://user-images.githubusercontent.com/20900883/51367590-f9b0cf00-1af3-11e9-8b5b-f8e219155b94.jpg)

And when door is opened there should be no no contact (**false**), MQTT payload says **true**:
```
Received zigbee message of type 'statusChange' with data '{"cid":"ssIasZone","zoneStatus":33}' of device 'CSW_ADUROLIGHT' (0x00158d0001cca9aa)
MQTT publish: topic 'zigbee2mqtt/0x00158d0001cca9aa', payload '{"contact":true,"linkquality":10}'
```
Opened door shows as a closed door:
![door_open](https://user-images.githubusercontent.com/20900883/51367693-7e9be880-1af4-11e9-81cc-dc87f2866f23.jpg)

**Comment by Koenkk** [comment] 2019-01-18 07:20
Sorry, I completely misread your post.

Could you change:
- https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/fromZigbee.js#L1223
- https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/fromZigbee.js#L1233
- to `!((zoneStatus & 1) > 0)`

and check if the problem is fixed?

**Comment by Kryzek** [comment] 2019-01-18 14:03
Yes, logic is now correct with these lines changed! Closed door shows up as a closed door and open one as an open one.

**Comment by Koenkk** [comment] 2019-01-18 14:14
Great, would you mind making a pr?

**Comment by Kryzek** [comment] 2019-01-18 14:20
I will get to do that later, it has been snowing and yard needs to be plowed out of snow.

**Comment by Kryzek** [comment] 2019-01-18 16:33
https://github.com/Koenkk/zigbee-shepherd-converters/pull/221 Thanks again Koen! :)

**Comment by Koenkk** [comment] 2019-01-18 18:01
Merged!

**Closed by Koenkk** 2019-01-18 18:01 UTC
